### ISSUE TITLE
Database Bug

### ISSUE THREAD

**Issue by Byteingpython** [Iridium-Development/IridiumTeams#15]
Iridium Skyblock throws this error every 5 Minutes and Missions reset on every restart
```
[13:10:28 WARN]: java.sql.SQLException: Unable to run insert stmt on object com.iridium.iridiumteams.database.TeamMissionData@12ba5986: INSERT INTO `team_mission_data` (`mission_id` ,`mission_index` ,`progress` ) VALUES (?,?,?)
[13:10:28 WARN]:        at IridiumSkyblock-4.0.0.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:139)
[13:10:28 WARN]:        at IridiumSkyblock-4.0.0.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:464)
[13:10:28 WARN]:        at IridiumSkyblock-4.0.0.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:337)
[13:10:28 WARN]:        at IridiumSkyblock-4.0.0.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:396)
[13:10:28 WARN]:        at IridiumSkyblock-4.0.0.jar//com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.save(TableManager.java:38)
[13:10:28 WARN]:        at IridiumSkyblock-4.0.0.jar//com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:201)
[13:10:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[13:10:28 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:10:28 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:10:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:10:28 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:10:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:10:28 WARN]: Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry '4-0' for key 'mission_id'
[13:10:28 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
[13:10:28 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[13:10:28 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[13:10:28 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
[13:10:28 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
[13:10:28 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
[13:10:28 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
[13:10:28 WARN]:        at IridiumSkyblock-4.0.0.jar//com.iridium.iridiumskyblock.dependencies.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:185)
[13:10:28 WARN]:        at IridiumSkyblock-4.0.0.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
[13:10:28 WARN]:        ... 11 more
```
Reading the Stacktrace, it seems to be related to IridiumTeams

**Comment by PeachesMLG** [comment]
was fixed in 4.0.4
